### ISSUE TITLE
Jupyter Notebook for Data Analysis

### ISSUE THREAD

**Issue by Gautier404** [Bruin-Racing-Baja/MOAT#21]
We collected and will collect a bunch of raw data . Create a jupyter notebook that can read in a file in https://github.com/Bruin-Racing-Baja/MOAT/tree/main/Winter2022DriveDayData and shows us graphs of:
linear position and engine rpm over time 
voltage & current over time
actuator motor over time
and anything else you might deem helpful

try to normalize things and make the graphs readable

**Comment by gettyv** [comment]
Sorry for the poor name, but far_future actually contains the current bit of development we have for now. Also, even though I am already working on this issue I wouldn't mind working with other people on it!

**Comment by Gautier404** [comment]
I added the ability to auto generate plots with multiple variables. The auto cropping definitely could use some work and we need to split our data files into runs so we can read them into our notebook easier.
